version: '3.8'
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
  
  reverse-proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./keys/server.crt:/etc/nginx/ssl/server.crt
      - ./keys/server.key:/etc/nginx/ssl/server.key
      - ./keys/client_bundle.crt:/etc/nginx/ssl/client_ca.crt
      - ./logs/:/var/log/nginx/
    ports:
      - 443:443

volumes:
  mongo-data:
    driver: local