version: '3.8'
services:

  mockin:
    profiles:
      - main
    build: .
    environment:
      - MOCKIN_DB_CONNECTION=mongodb://mongodb:27017/mockin
    ports:
      - 80:80

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  mongo-express:
    profiles:
      - dev
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      # Disable basic auth.
      ME_CONFIG_BASICAUTH_USERNAME: ""
      ME_CONFIG_BASICAUTH_PASSWORD: ""

  reverse-proxy:
    profiles:
      - dev
      - main
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./keys/server.crt:/etc/nginx/ssl/server.crt
      - ./keys/server.key:/etc/nginx/ssl/server.key
      - ./keys/client_ca.crt:/etc/nginx/ssl/client_ca.crt
      - ./logs/:/var/log/nginx/
    ports:
      - 443:443
    networks:
      default:
        aliases:
          - mockin.local
          - matls-mockin.local

  cs-httpd:
    profiles:
      - conformance
    build:
      context: ./conformance-suite/httpd
      dockerfile: Dockerfile-static
    ports:
     - "8443:8443"
    volumes:
     - ./conformance-suite/src/main/resources/:/usr/local/apache2/htdocs/
    depends_on:
     - cs-server

  cs-server:
    profiles:
      - conformance
    hostname: server
    image: openjdk:17-jdk-slim
    build:
      context: ./conformance-suite/server-dev
    ports:
     - "9999:9999"
    volumes:
     - ./conformance-suite/target/:/server/
    command: >
      java
      -Xdebug -Xrunjdwp:transport=dt_socket,address=*:9999,server=y,suspend=n
      -jar /server/libopin.jar
      -Djdk.tls.maxHandshakeMessageSize=65536
      --fintechlabs.base_url=https://localhost.emobix.co.uk:8443
      --fintechlabs.base_mtls_url=https://localhost.emobix.co.uk:8444
      --fintechlabs.devmode=true
      --fintechlabs.startredir=true
    links:
     - mongodb:mongodb
    depends_on:
     - mongodb
    logging:
      # limit logs retained on host
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "5"

  cs-builder:
    profiles:
      - build
    image: maven:3-openjdk-17
    volumes:
      - maven-cache:/root/.m2
      - ./conformance-suite:/usr/src/mymaven
    working_dir: /usr/src/mymaven
    command: mvn -B clean package -DskipTests=true

volumes:
  maven-cache:
    driver: local
  mongo-data:
    driver: local
