//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.1-0.20240908200014-2be24b11ae0f DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ConsentPermission.
const (
	ConsentPermissionCAPITALIZATIONTITLEEVENTSREAD                             ConsentPermission = "CAPITALIZATION_TITLE_EVENTS_READ"
	ConsentPermissionCAPITALIZATIONTITLEPLANINFOREAD                           ConsentPermission = "CAPITALIZATION_TITLE_PLANINFO_READ"
	ConsentPermissionCAPITALIZATIONTITLEREAD                                   ConsentPermission = "CAPITALIZATION_TITLE_READ"
	ConsentPermissionCAPITALIZATIONTITLESETTLEMENTSREAD                        ConsentPermission = "CAPITALIZATION_TITLE_SETTLEMENTS_READ"
	ConsentPermissionCAPITALIZATIONTITLEWITHDRAWALCREATE                       ConsentPermission = "CAPITALIZATION_TITLE_WITHDRAWAL_CREATE"
	ConsentPermissionCLAIMNOTIFICATIONREQUESTDAMAGECREATE                      ConsentPermission = "CLAIM_NOTIFICATION_REQUEST_DAMAGE_CREATE"
	ConsentPermissionCLAIMNOTIFICATIONREQUESTPERSONCREATE                      ConsentPermission = "CLAIM_NOTIFICATION_REQUEST_PERSON_CREATE"
	ConsentPermissionCONTRACTLIFEPENSIONLEADCREATE                             ConsentPermission = "CONTRACT_LIFE_PENSION_LEAD_CREATE"
	ConsentPermissionCONTRACTLIFEPENSIONLEADPORTABILITYCREATE                  ConsentPermission = "CONTRACT_LIFE_PENSION_LEAD_PORTABILITY_CREATE"
	ConsentPermissionCONTRACTLIFEPENSIONLEADPORTABILITYUPDATE                  ConsentPermission = "CONTRACT_LIFE_PENSION_LEAD_PORTABILITY_UPDATE"
	ConsentPermissionCONTRACTLIFEPENSIONLEADUPDATE                             ConsentPermission = "CONTRACT_LIFE_PENSION_LEAD_UPDATE"
	ConsentPermissionCONTRACTPENSIONPLANLEADCREATE                             ConsentPermission = "CONTRACT_PENSION_PLAN_LEAD_CREATE"
	ConsentPermissionCONTRACTPENSIONPLANLEADPORTABILITYCREATE                  ConsentPermission = "CONTRACT_PENSION_PLAN_LEAD_PORTABILITY_CREATE"
	ConsentPermissionCONTRACTPENSIONPLANLEADPORTABILITYUPDATE                  ConsentPermission = "CONTRACT_PENSION_PLAN_LEAD_PORTABILITY_UPDATE"
	ConsentPermissionCONTRACTPENSIONPLANLEADUPDATE                             ConsentPermission = "CONTRACT_PENSION_PLAN_LEAD_UPDATE"
	ConsentPermissionCUSTOMERSBUSINESSADDITIONALINFOREAD                       ConsentPermission = "CUSTOMERS_BUSINESS_ADDITIONALINFO_READ"
	ConsentPermissionCUSTOMERSBUSINESSIDENTIFICATIONSREAD                      ConsentPermission = "CUSTOMERS_BUSINESS_IDENTIFICATIONS_READ"
	ConsentPermissionCUSTOMERSBUSINESSQUALIFICATIONREAD                        ConsentPermission = "CUSTOMERS_BUSINESS_QUALIFICATION_READ"
	ConsentPermissionCUSTOMERSPERSONALADDITIONALINFOREAD                       ConsentPermission = "CUSTOMERS_PERSONAL_ADDITIONALINFO_READ"
	ConsentPermissionCUSTOMERSPERSONALIDENTIFICATIONSREAD                      ConsentPermission = "CUSTOMERS_PERSONAL_IDENTIFICATIONS_READ"
	ConsentPermissionCUSTOMERSPERSONALQUALIFICATIONREAD                        ConsentPermission = "CUSTOMERS_PERSONAL_QUALIFICATION_READ"
	ConsentPermissionDAMAGESANDPEOPLEACCEPTANCEANDBRANCHESABROADCLAIMREAD      ConsentPermission = "DAMAGES_AND_PEOPLE_ACCEPTANCE_AND_BRANCHES_ABROAD_CLAIM_READ"
	ConsentPermissionDAMAGESANDPEOPLEACCEPTANCEANDBRANCHESABROADPOLICYINFOREAD ConsentPermission = "DAMAGES_AND_PEOPLE_ACCEPTANCE_AND_BRANCHES_ABROAD_POLICYINFO_READ"
	ConsentPermissionDAMAGESANDPEOPLEACCEPTANCEANDBRANCHESABROADPREMIUMREAD    ConsentPermission = "DAMAGES_AND_PEOPLE_ACCEPTANCE_AND_BRANCHES_ABROAD_PREMIUM_READ"
	ConsentPermissionDAMAGESANDPEOPLEACCEPTANCEANDBRANCHESABROADREAD           ConsentPermission = "DAMAGES_AND_PEOPLE_ACCEPTANCE_AND_BRANCHES_ABROAD_READ"
	ConsentPermissionDAMAGESANDPEOPLEAUTOCLAIMREAD                             ConsentPermission = "DAMAGES_AND_PEOPLE_AUTO_CLAIM_READ"
	ConsentPermissionDAMAGESANDPEOPLEAUTOPOLICYINFOREAD                        ConsentPermission = "DAMAGES_AND_PEOPLE_AUTO_POLICYINFO_READ"
	ConsentPermissionDAMAGESANDPEOPLEAUTOPREMIUMREAD                           ConsentPermission = "DAMAGES_AND_PEOPLE_AUTO_PREMIUM_READ"
	ConsentPermissionDAMAGESANDPEOPLEAUTOREAD                                  ConsentPermission = "DAMAGES_AND_PEOPLE_AUTO_READ"
	ConsentPermissionDAMAGESANDPEOPLEFINANCIALRISKSCLAIMREAD                   ConsentPermission = "DAMAGES_AND_PEOPLE_FINANCIAL_RISKS_CLAIM_READ"
	ConsentPermissionDAMAGESANDPEOPLEFINANCIALRISKSPOLICYINFOREAD              ConsentPermission = "DAMAGES_AND_PEOPLE_FINANCIAL_RISKS_POLICYINFO_READ"
	ConsentPermissionDAMAGESANDPEOPLEFINANCIALRISKSPREMIUMREAD                 ConsentPermission = "DAMAGES_AND_PEOPLE_FINANCIAL_RISKS_PREMIUM_READ"
	ConsentPermissionDAMAGESANDPEOPLEFINANCIALRISKSREAD                        ConsentPermission = "DAMAGES_AND_PEOPLE_FINANCIAL_RISKS_READ"
	ConsentPermissionDAMAGESANDPEOPLEHOUSINGCLAIMREAD                          ConsentPermission = "DAMAGES_AND_PEOPLE_HOUSING_CLAIM_READ"
	ConsentPermissionDAMAGESANDPEOPLEHOUSINGPOLICYINFOREAD                     ConsentPermission = "DAMAGES_AND_PEOPLE_HOUSING_POLICYINFO_READ"
	ConsentPermissionDAMAGESANDPEOPLEHOUSINGPREMIUMREAD                        ConsentPermission = "DAMAGES_AND_PEOPLE_HOUSING_PREMIUM_READ"
	ConsentPermissionDAMAGESANDPEOPLEHOUSINGREAD                               ConsentPermission = "DAMAGES_AND_PEOPLE_HOUSING_READ"
	ConsentPermissionDAMAGESANDPEOPLEPATRIMONIALCLAIMREAD                      ConsentPermission = "DAMAGES_AND_PEOPLE_PATRIMONIAL_CLAIM_READ"
	ConsentPermissionDAMAGESANDPEOPLEPATRIMONIALPOLICYINFOREAD                 ConsentPermission = "DAMAGES_AND_PEOPLE_PATRIMONIAL_POLICYINFO_READ"
	ConsentPermissionDAMAGESANDPEOPLEPATRIMONIALPREMIUMREAD                    ConsentPermission = "DAMAGES_AND_PEOPLE_PATRIMONIAL_PREMIUM_READ"
	ConsentPermissionDAMAGESANDPEOPLEPATRIMONIALREAD                           ConsentPermission = "DAMAGES_AND_PEOPLE_PATRIMONIAL_READ"
	ConsentPermissionDAMAGESANDPEOPLEPERSONCLAIMREAD                           ConsentPermission = "DAMAGES_AND_PEOPLE_PERSON_CLAIM_READ"
	ConsentPermissionDAMAGESANDPEOPLEPERSONPOLICYINFOREAD                      ConsentPermission = "DAMAGES_AND_PEOPLE_PERSON_POLICYINFO_READ"
	ConsentPermissionDAMAGESANDPEOPLEPERSONPREMIUMREAD                         ConsentPermission = "DAMAGES_AND_PEOPLE_PERSON_PREMIUM_READ"
	ConsentPermissionDAMAGESANDPEOPLEPERSONREAD                                ConsentPermission = "DAMAGES_AND_PEOPLE_PERSON_READ"
	ConsentPermissionDAMAGESANDPEOPLERESPONSIBILITYCLAIMREAD                   ConsentPermission = "DAMAGES_AND_PEOPLE_RESPONSIBILITY_CLAIM_READ"
	ConsentPermissionDAMAGESANDPEOPLERESPONSIBILITYPOLICYINFOREAD              ConsentPermission = "DAMAGES_AND_PEOPLE_RESPONSIBILITY_POLICYINFO_READ"
	ConsentPermissionDAMAGESANDPEOPLERESPONSIBILITYPREMIUMREAD                 ConsentPermission = "DAMAGES_AND_PEOPLE_RESPONSIBILITY_PREMIUM_READ"
	ConsentPermissionDAMAGESANDPEOPLERESPONSIBILITYREAD                        ConsentPermission = "DAMAGES_AND_PEOPLE_RESPONSIBILITY_READ"
	ConsentPermissionDAMAGESANDPEOPLERURALCLAIMREAD                            ConsentPermission = "DAMAGES_AND_PEOPLE_RURAL_CLAIM_READ"
	ConsentPermissionDAMAGESANDPEOPLERURALPOLICYINFOREAD                       ConsentPermission = "DAMAGES_AND_PEOPLE_RURAL_POLICYINFO_READ"
	ConsentPermissionDAMAGESANDPEOPLERURALPREMIUMREAD                          ConsentPermission = "DAMAGES_AND_PEOPLE_RURAL_PREMIUM_READ"
	ConsentPermissionDAMAGESANDPEOPLERURALREAD                                 ConsentPermission = "DAMAGES_AND_PEOPLE_RURAL_READ"
	ConsentPermissionDAMAGESANDPEOPLETRANSPORTCLAIMREAD                        ConsentPermission = "DAMAGES_AND_PEOPLE_TRANSPORT_CLAIM_READ"
	ConsentPermissionDAMAGESANDPEOPLETRANSPORTPOLICYINFOREAD                   ConsentPermission = "DAMAGES_AND_PEOPLE_TRANSPORT_POLICYINFO_READ"
	ConsentPermissionDAMAGESANDPEOPLETRANSPORTPREMIUMREAD                      ConsentPermission = "DAMAGES_AND_PEOPLE_TRANSPORT_PREMIUM_READ"
	ConsentPermissionDAMAGESANDPEOPLETRANSPORTREAD                             ConsentPermission = "DAMAGES_AND_PEOPLE_TRANSPORT_READ"
	ConsentPermissionENDORSEMENTREQUESTCREATE                                  ConsentPermission = "ENDORSEMENT_REQUEST_CREATE"
	ConsentPermissionFINANCIALASSISTANCECONTRACTINFOREAD                       ConsentPermission = "FINANCIAL_ASSISTANCE_CONTRACTINFO_READ"
	ConsentPermissionFINANCIALASSISTANCEMOVEMENTSREAD                          ConsentPermission = "FINANCIAL_ASSISTANCE_MOVEMENTS_READ"
	ConsentPermissionFINANCIALASSISTANCEREAD                                   ConsentPermission = "FINANCIAL_ASSISTANCE_READ"
	ConsentPermissionLIFEPENSIONCLAIM                                          ConsentPermission = "LIFE_PENSION_CLAIM"
	ConsentPermissionLIFEPENSIONCONTRACTINFOREAD                               ConsentPermission = "LIFE_PENSION_CONTRACTINFO_READ"
	ConsentPermissionLIFEPENSIONMOVEMENTSREAD                                  ConsentPermission = "LIFE_PENSION_MOVEMENTS_READ"
	ConsentPermissionLIFEPENSIONPORTABILITIESREAD                              ConsentPermission = "LIFE_PENSION_PORTABILITIES_READ"
	ConsentPermissionLIFEPENSIONREAD                                           ConsentPermission = "LIFE_PENSION_READ"
	ConsentPermissionLIFEPENSIONWITHDRAWALSREAD                                ConsentPermission = "LIFE_PENSION_WITHDRAWALS_READ"
	ConsentPermissionPENSIONPLANCLAIM                                          ConsentPermission = "PENSION_PLAN_CLAIM"
	ConsentPermissionPENSIONPLANCONTRACTINFOREAD                               ConsentPermission = "PENSION_PLAN_CONTRACTINFO_READ"
	ConsentPermissionPENSIONPLANMOVEMENTSREAD                                  ConsentPermission = "PENSION_PLAN_MOVEMENTS_READ"
	ConsentPermissionPENSIONPLANPORTABILITIESREAD                              ConsentPermission = "PENSION_PLAN_PORTABILITIES_READ"
	ConsentPermissionPENSIONPLANREAD                                           ConsentPermission = "PENSION_PLAN_READ"
	ConsentPermissionPENSIONPLANWITHDRAWALSREAD                                ConsentPermission = "PENSION_PLAN_WITHDRAWALS_READ"
	ConsentPermissionPENSIONWITHDRAWALCREATE                                   ConsentPermission = "PENSION_WITHDRAWAL_CREATE"
	ConsentPermissionQUOTEACCEPTANCEANDBRANCHESABROADLEADCREATE                ConsentPermission = "QUOTE_ACCEPTANCE_AND_BRANCHES_ABROAD_LEAD_CREATE"
	ConsentPermissionQUOTEACCEPTANCEANDBRANCHESABROADLEADUPDATE                ConsentPermission = "QUOTE_ACCEPTANCE_AND_BRANCHES_ABROAD_LEAD_UPDATE"
	ConsentPermissionQUOTEAUTOCREATE                                           ConsentPermission = "QUOTE_AUTO_CREATE"
	ConsentPermissionQUOTEAUTOLEADCREATE                                       ConsentPermission = "QUOTE_AUTO_LEAD_CREATE"
	ConsentPermissionQUOTEAUTOLEADUPDATE                                       ConsentPermission = "QUOTE_AUTO_LEAD_UPDATE"
	ConsentPermissionQUOTEAUTOREAD                                             ConsentPermission = "QUOTE_AUTO_READ"
	ConsentPermissionQUOTEAUTOUPDATE                                           ConsentPermission = "QUOTE_AUTO_UPDATE"
	ConsentPermissionQUOTECAPITALIZATIONTITLECREATE                            ConsentPermission = "QUOTE_CAPITALIZATION_TITLE_CREATE"
	ConsentPermissionQUOTECAPITALIZATIONTITLELEADCREATE                        ConsentPermission = "QUOTE_CAPITALIZATION_TITLE_LEAD_CREATE"
	ConsentPermissionQUOTECAPITALIZATIONTITLELEADUPDATE                        ConsentPermission = "QUOTE_CAPITALIZATION_TITLE_LEAD_UPDATE"
	ConsentPermissionQUOTECAPITALIZATIONTITLERAFFLECREATE                      ConsentPermission = "QUOTE_CAPITALIZATION_TITLE_RAFFLE_CREATE"
	ConsentPermissionQUOTECAPITALIZATIONTITLEREAD                              ConsentPermission = "QUOTE_CAPITALIZATION_TITLE_READ"
	ConsentPermissionQUOTECAPITALIZATIONTITLEUPDATE                            ConsentPermission = "QUOTE_CAPITALIZATION_TITLE_UPDATE"
	ConsentPermissionQUOTEFINANCIALRISKLEADCREATE                              ConsentPermission = "QUOTE_FINANCIAL_RISK_LEAD_CREATE"
	ConsentPermissionQUOTEFINANCIALRISKLEADUPDATE                              ConsentPermission = "QUOTE_FINANCIAL_RISK_LEAD_UPDATE"
	ConsentPermissionQUOTEHOUSINGLEADCREATE                                    ConsentPermission = "QUOTE_HOUSING_LEAD_CREATE"
	ConsentPermissionQUOTEHOUSINGLEADUPDATE                                    ConsentPermission = "QUOTE_HOUSING_LEAD_UPDATE"
	ConsentPermissionQUOTEPATRIMONIALBUSINESSCREATE                            ConsentPermission = "QUOTE_PATRIMONIAL_BUSINESS_CREATE"
	ConsentPermissionQUOTEPATRIMONIALBUSINESSREAD                              ConsentPermission = "QUOTE_PATRIMONIAL_BUSINESS_READ"
	ConsentPermissionQUOTEPATRIMONIALBUSINESSUPDATE                            ConsentPermission = "QUOTE_PATRIMONIAL_BUSINESS_UPDATE"
	ConsentPermissionQUOTEPATRIMONIALCONDOMINIUMCREATE                         ConsentPermission = "QUOTE_PATRIMONIAL_CONDOMINIUM_CREATE"
	ConsentPermissionQUOTEPATRIMONIALCONDOMINIUMREAD                           ConsentPermission = "QUOTE_PATRIMONIAL_CONDOMINIUM_READ"
	ConsentPermissionQUOTEPATRIMONIALCONDOMINIUMUPDATE                         ConsentPermission = "QUOTE_PATRIMONIAL_CONDOMINIUM_UPDATE"
	ConsentPermissionQUOTEPATRIMONIALDIVERSERISKSCREATE                        ConsentPermission = "QUOTE_PATRIMONIAL_DIVERSE_RISKS_CREATE"
	ConsentPermissionQUOTEPATRIMONIALDIVERSERISKSREAD                          ConsentPermission = "QUOTE_PATRIMONIAL_DIVERSE_RISKS_READ"
	ConsentPermissionQUOTEPATRIMONIALDIVERSERISKSUPDATE                        ConsentPermission = "QUOTE_PATRIMONIAL_DIVERSE_RISKS_UPDATE"
	ConsentPermissionQUOTEPATRIMONIALHOMECREATE                                ConsentPermission = "QUOTE_PATRIMONIAL_HOME_CREATE"
	ConsentPermissionQUOTEPATRIMONIALHOMEREAD                                  ConsentPermission = "QUOTE_PATRIMONIAL_HOME_READ"
	ConsentPermissionQUOTEPATRIMONIALHOMEUPDATE                                ConsentPermission = "QUOTE_PATRIMONIAL_HOME_UPDATE"
	ConsentPermissionQUOTEPATRIMONIALLEADCREATE                                ConsentPermission = "QUOTE_PATRIMONIAL_LEAD_CREATE"
	ConsentPermissionQUOTEPATRIMONIALLEADUPDATE                                ConsentPermission = "QUOTE_PATRIMONIAL_LEAD_UPDATE"
	ConsentPermissionQUOTEPERSONLEADCREATE                                     ConsentPermission = "QUOTE_PERSON_LEAD_CREATE"
	ConsentPermissionQUOTEPERSONLEADUPDATE                                     ConsentPermission = "QUOTE_PERSON_LEAD_UPDATE"
	ConsentPermissionQUOTEPERSONLIFECREATE                                     ConsentPermission = "QUOTE_PERSON_LIFE_CREATE"
	ConsentPermissionQUOTEPERSONLIFEREAD                                       ConsentPermission = "QUOTE_PERSON_LIFE_READ"
	ConsentPermissionQUOTEPERSONLIFEUPDATE                                     ConsentPermission = "QUOTE_PERSON_LIFE_UPDATE"
	ConsentPermissionQUOTEPERSONTRAVELCREATE                                   ConsentPermission = "QUOTE_PERSON_TRAVEL_CREATE"
	ConsentPermissionQUOTEPERSONTRAVELREAD                                     ConsentPermission = "QUOTE_PERSON_TRAVEL_READ"
	ConsentPermissionQUOTEPERSONTRAVELUPDATE                                   ConsentPermission = "QUOTE_PERSON_TRAVEL_UPDATE"
	ConsentPermissionQUOTERESPONSIBILITYLEADCREATE                             ConsentPermission = "QUOTE_RESPONSIBILITY_LEAD_CREATE"
	ConsentPermissionQUOTERESPONSIBILITYLEADUPDATE                             ConsentPermission = "QUOTE_RESPONSIBILITY_LEAD_UPDATE"
	ConsentPermissionQUOTERURALLEADCREATE                                      ConsentPermission = "QUOTE_RURAL_LEAD_CREATE"
	ConsentPermissionQUOTERURALLEADUPDATE                                      ConsentPermission = "QUOTE_RURAL_LEAD_UPDATE"
	ConsentPermissionQUOTETRANSPORTLEADCREATE                                  ConsentPermission = "QUOTE_TRANSPORT_LEAD_CREATE"
	ConsentPermissionQUOTETRANSPORTLEADUPDATE                                  ConsentPermission = "QUOTE_TRANSPORT_LEAD_UPDATE"
	ConsentPermissionRESOURCESREAD                                             ConsentPermission = "RESOURCES_READ"
)

// Defines values for ConsentRejectedBy.
const (
	ConsentRejectedByASPSP ConsentRejectedBy = "ASPSP"
	ConsentRejectedByTPP   ConsentRejectedBy = "TPP"
	ConsentRejectedByUSER  ConsentRejectedBy = "USER"
)

// Defines values for ConsentRejectedReasonCode.
const (
	ConsentRejectedReasonCodeCONSENTEXPIRED           ConsentRejectedReasonCode = "CONSENT_EXPIRED"
	ConsentRejectedReasonCodeCONSENTMAXDATEREACHED    ConsentRejectedReasonCode = "CONSENT_MAX_DATE_REACHED"
	ConsentRejectedReasonCodeCONSENTTECHNICALISSUE    ConsentRejectedReasonCode = "CONSENT_TECHNICAL_ISSUE"
	ConsentRejectedReasonCodeCUSTOMERMANUALLYREJECTED ConsentRejectedReasonCode = "CUSTOMER_MANUALLY_REJECTED"
	ConsentRejectedReasonCodeCUSTOMERMANUALLYREVOKED  ConsentRejectedReasonCode = "CUSTOMER_MANUALLY_REVOKED"
	ConsentRejectedReasonCodeINTERNALSECURITYREASON   ConsentRejectedReasonCode = "INTERNAL_SECURITY_REASON"
)

// Defines values for ConsentResponseDataV2ClaimNotificationInformationDocumentType.
const (
	ConsentResponseDataV2ClaimNotificationInformationDocumentTypeAPOLICEFROTAAUTOMOVEL      ConsentResponseDataV2ClaimNotificationInformationDocumentType = "APOLICE_FROTA_AUTOMOVEL"
	ConsentResponseDataV2ClaimNotificationInformationDocumentTypeAPOLICEINDIVIDUAL          ConsentResponseDataV2ClaimNotificationInformationDocumentType = "APOLICE_INDIVIDUAL"
	ConsentResponseDataV2ClaimNotificationInformationDocumentTypeAPOLICEINDIVIDUALAUTOMOVEL ConsentResponseDataV2ClaimNotificationInformationDocumentType = "APOLICE_INDIVIDUAL_AUTOMOVEL"
	ConsentResponseDataV2ClaimNotificationInformationDocumentTypeBILHETE                    ConsentResponseDataV2ClaimNotificationInformationDocumentType = "BILHETE"
	ConsentResponseDataV2ClaimNotificationInformationDocumentTypeCERTIFICADO                ConsentResponseDataV2ClaimNotificationInformationDocumentType = "CERTIFICADO"
	ConsentResponseDataV2ClaimNotificationInformationDocumentTypeCERTIFICADOAUTOMOVEL       ConsentResponseDataV2ClaimNotificationInformationDocumentType = "CERTIFICADO_AUTOMOVEL"
)

// Defines values for ConsentStatus.
const (
	ConsentStatusAUTHORISED            ConsentStatus = "AUTHORISED"
	ConsentStatusAWAITINGAUTHORISATION ConsentStatus = "AWAITING_AUTHORISATION"
	ConsentStatusCONSUMED              ConsentStatus = "CONSUMED"
	ConsentStatusREJECTED              ConsentStatus = "REJECTED"
)

// Defines values for CreateConsentRequestV2DataClaimNotificationInformationDocumentType.
const (
	CreateConsentRequestV2DataClaimNotificationInformationDocumentTypeAPOLICEFROTAAUTOMOVEL      CreateConsentRequestV2DataClaimNotificationInformationDocumentType = "APOLICE_FROTA_AUTOMOVEL"
	CreateConsentRequestV2DataClaimNotificationInformationDocumentTypeAPOLICEINDIVIDUAL          CreateConsentRequestV2DataClaimNotificationInformationDocumentType = "APOLICE_INDIVIDUAL"
	CreateConsentRequestV2DataClaimNotificationInformationDocumentTypeAPOLICEINDIVIDUALAUTOMOVEL CreateConsentRequestV2DataClaimNotificationInformationDocumentType = "APOLICE_INDIVIDUAL_AUTOMOVEL"
	CreateConsentRequestV2DataClaimNotificationInformationDocumentTypeBILHETE                    CreateConsentRequestV2DataClaimNotificationInformationDocumentType = "BILHETE"
	CreateConsentRequestV2DataClaimNotificationInformationDocumentTypeCERTIFICADO                CreateConsentRequestV2DataClaimNotificationInformationDocumentType = "CERTIFICADO"
	CreateConsentRequestV2DataClaimNotificationInformationDocumentTypeCERTIFICADOAUTOMOVEL       CreateConsentRequestV2DataClaimNotificationInformationDocumentType = "CERTIFICADO_AUTOMOVEL"
)

// Defines values for EndorsementType.
const (
	EndorsementTypeALTERACAO    EndorsementType = "ALTERACAO"
	EndorsementTypeCANCELAMENTO EndorsementType = "CANCELAMENTO"
	EndorsementTypeEXCLUSAO     EndorsementType = "EXCLUSAO"
	EndorsementTypeINCLUSAO     EndorsementType = "INCLUSAO"
)

// BusinessEntity defines model for BusinessEntity.
type BusinessEntity struct {
	Document struct {
		Identification string `json:"identification"`
		Rel            string `json:"rel"`
	} `json:"document"`
}

// ConsentPermission defines model for ConsentPermission.
type ConsentPermission string

// ConsentRejectedBy defines model for ConsentRejectedBy.
type ConsentRejectedBy string

// ConsentRejectedReason defines model for ConsentRejectedReason.
type ConsentRejectedReason struct {
	AdditionalInformation *string                   `json:"additionalInformation,omitempty"`
	Code                  ConsentRejectedReasonCode `json:"code"`
}

// ConsentRejectedReasonCode defines model for ConsentRejectedReasonCode.
type ConsentRejectedReasonCode string

// ConsentRejection defines model for ConsentRejection.
type ConsentRejection struct {
	Reason     ConsentRejectedReason `json:"reason"`
	RejectedBy ConsentRejectedBy     `json:"rejectedBy"`
}

// ConsentResponseDataV2 defines model for ConsentResponseDataV2.
type ConsentResponseDataV2 struct {
	ClaimNotificationInformation *struct {
		// DocumentType Tipo de Documento Emitido.
		DocumentType          ConsentResponseDataV2ClaimNotificationInformationDocumentType `json:"documentType"`
		GroupCertificateId    *string                                                       `json:"groupCertificateId,omitempty"`
		OccurrenceDate        openapi_types.Date                                            `json:"occurrenceDate"`
		OccurrenceDescription string                                                        `json:"occurrenceDescription"`
		OccurrenceTime        *string                                                       `json:"occurrenceTime,omitempty"`
		PolicyNumber          string                                                        `json:"policyNumber"`
	} `json:"claimNotificationInformation,omitempty"`
	ConsentId              string   `json:"consentId"`
	CreationDateTime       DateTime `json:"creationDateTime"`
	EndorsementInformation *struct {
		EndorsementType    EndorsementType `json:"endorsementType"`
		PolicyNumber       string          `json:"policyNumber"`
		RequestDescription string          `json:"requestDescription"`
	} `json:"endorsementInformation,omitempty"`
	ExpirationDateTime   DateTime            `json:"expirationDateTime"`
	Permissions          []ConsentPermission `json:"permissions"`
	Rejection            *ConsentRejection   `json:"rejection,omitempty"`
	Status               ConsentStatus       `json:"status"`
	StatusUpdateDateTime DateTime            `json:"statusUpdateDateTime"`
}

// ConsentResponseDataV2ClaimNotificationInformationDocumentType Tipo de Documento Emitido.
type ConsentResponseDataV2ClaimNotificationInformationDocumentType string

// ConsentResponseV2 defines model for ConsentResponseV2.
type ConsentResponseV2 struct {
	Data  ConsentResponseDataV2 `json:"data"`
	Links *Links                `json:"links,omitempty"`
	Meta  *Meta                 `json:"meta,omitempty"`
}

// ConsentStatus defines model for ConsentStatus.
type ConsentStatus string

// CreateConsentRequestV2 defines model for CreateConsentRequestV2.
type CreateConsentRequestV2 struct {
	Data struct {
		BusinessEntity               *BusinessEntity `json:"businessEntity,omitempty"`
		ClaimNotificationInformation *struct {
			DocumentType          CreateConsentRequestV2DataClaimNotificationInformationDocumentType `json:"documentType"`
			GroupCertificateId    *string                                                            `json:"groupCertificateId,omitempty"`
			OccurrenceDate        openapi_types.Date                                                 `json:"occurrenceDate"`
			OccurrenceDescription string                                                             `json:"occurrenceDescription"`
			OccurrenceTime        *string                                                            `json:"occurrenceTime,omitempty"`
			PolicyNumber          string                                                             `json:"policyNumber"`
		} `json:"claimNotificationInformation,omitempty"`
		EndorsementInformation *struct {
			EndorsementType    EndorsementType `json:"endorsementType"`
			PolicyNumber       string          `json:"policyNumber"`
			RequestDescription string          `json:"requestDescription"`
		} `json:"endorsementInformation,omitempty"`
		ExpirationDateTime DateTime            `json:"expirationDateTime"`
		LoggedUser         LoggedUser          `json:"loggedUser"`
		Permissions        []ConsentPermission `json:"permissions"`
	} `json:"data"`
}

// CreateConsentRequestV2DataClaimNotificationInformationDocumentType defines model for CreateConsentRequestV2.Data.ClaimNotificationInformation.DocumentType.
type CreateConsentRequestV2DataClaimNotificationInformationDocumentType string

// EndorsementType defines model for EndorsementType.
type EndorsementType string

// Error defines model for Error.
type Error struct {
	Code            string   `json:"code"`
	Detail          string   `json:"detail"`
	RequestDateTime DateTime `json:"requestDateTime"`
	Title           string   `json:"title"`
}

// Links defines model for Links.
type Links struct {
	First *string `json:"first,omitempty"`
	Last  *string `json:"last,omitempty"`
	Next  *string `json:"next,omitempty"`
	Prev  *string `json:"prev,omitempty"`
	Self  string  `json:"self"`
}

// LoggedUser defines model for LoggedUser.
type LoggedUser struct {
	Document struct {
		Identification string `json:"identification"`
		Rel            string `json:"rel"`
	} `json:"document"`
}

// Meta defines model for Meta.
type Meta struct {
	TotalPages   int32 `json:"totalPages"`
	TotalRecords int32 `json:"totalRecords"`
}

// ResponseError defines model for ResponseError.
type ResponseError struct {
	Errors []Error `json:"errors"`
	Meta   *Meta   `json:"meta,omitempty"`
}

// ConsentId defines model for consentId.
type ConsentId = string

// CreateConsentV2JSONRequestBody defines body for CreateConsentV2 for application/json ContentType.
type CreateConsentV2JSONRequestBody = CreateConsentRequestV2

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /consents/v2/consents)
	CreateConsentV2(w http.ResponseWriter, r *http.Request)

	// (DELETE /consents/v2/consents/{consentId})
	DeleteConsentV2(w http.ResponseWriter, r *http.Request, consentId ConsentId)

	// (GET /consents/v2/consents/{consentId})
	ConsentV2(w http.ResponseWriter, r *http.Request, consentId ConsentId)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreateConsentV2 operation middleware
func (siw *ServerInterfaceWrapper) CreateConsentV2(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateConsentV2(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteConsentV2 operation middleware
func (siw *ServerInterfaceWrapper) DeleteConsentV2(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "consentId" -------------
	var consentId ConsentId

	err = runtime.BindStyledParameterWithOptions("simple", "consentId", r.PathValue("consentId"), &consentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "consentId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteConsentV2(w, r, consentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ConsentV2 operation middleware
func (siw *ServerInterfaceWrapper) ConsentV2(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "consentId" -------------
	var consentId ConsentId

	err = runtime.BindStyledParameterWithOptions("simple", "consentId", r.PathValue("consentId"), &consentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "consentId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ConsentV2(w, r, consentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       *http.ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m *http.ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m *http.ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/consents/v2/consents", wrapper.CreateConsentV2)
	m.HandleFunc("DELETE "+options.BaseURL+"/consents/v2/consents/{consentId}", wrapper.DeleteConsentV2)
	m.HandleFunc("GET "+options.BaseURL+"/consents/v2/consents/{consentId}", wrapper.ConsentV2)

	return m
}

type CreateConsentV2RequestObject struct {
	Body *CreateConsentV2JSONRequestBody
}

type CreateConsentV2ResponseObject interface {
	VisitCreateConsentV2Response(w http.ResponseWriter) error
}

type CreateConsentV2201JSONResponse ConsentResponseV2

func (response CreateConsentV2201JSONResponse) VisitCreateConsentV2Response(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type DeleteConsentV2RequestObject struct {
	ConsentId ConsentId `json:"consentId"`
}

type DeleteConsentV2ResponseObject interface {
	VisitDeleteConsentV2Response(w http.ResponseWriter) error
}

type DeleteConsentV2204Response struct {
}

func (response DeleteConsentV2204Response) VisitDeleteConsentV2Response(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type ConsentV2RequestObject struct {
	ConsentId ConsentId `json:"consentId"`
}

type ConsentV2ResponseObject interface {
	VisitConsentV2Response(w http.ResponseWriter) error
}

type ConsentV2200JSONResponse ConsentResponseV2

func (response ConsentV2200JSONResponse) VisitConsentV2Response(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (POST /consents/v2/consents)
	CreateConsentV2(ctx context.Context, request CreateConsentV2RequestObject) (CreateConsentV2ResponseObject, error)

	// (DELETE /consents/v2/consents/{consentId})
	DeleteConsentV2(ctx context.Context, request DeleteConsentV2RequestObject) (DeleteConsentV2ResponseObject, error)

	// (GET /consents/v2/consents/{consentId})
	ConsentV2(ctx context.Context, request ConsentV2RequestObject) (ConsentV2ResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// CreateConsentV2 operation middleware
func (sh *strictHandler) CreateConsentV2(w http.ResponseWriter, r *http.Request) {
	var request CreateConsentV2RequestObject

	var body CreateConsentV2JSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateConsentV2(ctx, request.(CreateConsentV2RequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateConsentV2")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateConsentV2ResponseObject); ok {
		if err := validResponse.VisitCreateConsentV2Response(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteConsentV2 operation middleware
func (sh *strictHandler) DeleteConsentV2(w http.ResponseWriter, r *http.Request, consentId ConsentId) {
	var request DeleteConsentV2RequestObject

	request.ConsentId = consentId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteConsentV2(ctx, request.(DeleteConsentV2RequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteConsentV2")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteConsentV2ResponseObject); ok {
		if err := validResponse.VisitDeleteConsentV2Response(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ConsentV2 operation middleware
func (sh *strictHandler) ConsentV2(w http.ResponseWriter, r *http.Request, consentId ConsentId) {
	var request ConsentV2RequestObject

	request.ConsentId = consentId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ConsentV2(ctx, request.(ConsentV2RequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ConsentV2")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ConsentV2ResponseObject); ok {
		if err := validResponse.VisitConsentV2Response(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xae3ebyBX/KulsepoHsh5O9jTq6UnHMF5PF4HCw3kYrQ4RY4dUAgooteuj794zDCAG",
	"RoCy9SY9Xf8lc3/3zn3N3DsX7sEq3ERhQII0AdN7ELmxuyEpibP/VmGQkCDFHv3HD8AURG76CUggcDcE",
	"TCt0CcTkn1s/Jh6YpvGWSCBZfSIblzJu3FuVBDfpJzCdvPxRojJSElNpv2zjYHrlDv4NBx9Gg1eL/c/B",
	"4n4knY53FeqTp88lxxmcTP/6t788Xv7h2Z/+6DjD1z8snj8GEkjvIqpQksZ+cAN2u12hQGbH2TbxA5Ik",
	"KEj99I4+cT3PT/0wcNfzOIxInPokAdNrd50QCUSVR/fAC1fbDQnSI9l8jwSpf+2vXMpQ88P4BecGx/Hu",
	"xy92AkOoX9c1Zp73Cg4+LO6FzLtqVK7qGjHRi5Ir/PiZrNIGV2l+EykBmSXAnMQbP0lyO0mw3VBO2TYt",
	"fYYMczlHhqlrUF1iBWkWPscytLCumUsDQQVIIiRUFEwxUMXaud4CfGNDtZTYxJ3ZJtaQaXYvXSL7Sjyg",
	"IpxjC6r4A2O3sKWiVtpchVqnAHSJNMtshZjIslQ0q+LmSDMpgC4hfCbrmmVA2aquzwFm+mWLyLluWPAM",
	"q9jCSIx4i60LxYBvoSqmyyrEMyABFZ+jZUHJgdwzkaYcoKEpRxVqyiEEmvIK5JqeYw1qMqYpaprYtKAm",
	"l/EV0kSaC4ENCxQ4gz8hcwk1ZTlH+pwmC7QMPNM1ytoPNddVLL+vLt7FYKAZtmc90ZlbWrAGMue6ZuLM",
	"9+/7A3upXefp1LzG0KW8ZUDNpKnTC9NL5Qq8U9s9tkvRfT4Z2PzZPALZS+kGU6fqdY7ONLGN1oxm9H5J",
	"waDduZDhuhSDtqV3kXupxZCdWmWwLqUudFqDfuqB6KVaCe7UrkB2ek2W0ZydavTpmQE1+YJCzgwdKl/P",
	"2M/THTK6Y9AuoMt41pp0A/qdzDm2+1BmQE45pCm6YWZFZWmgNzYyraVsIGgh2kRkSE23qr0OwzDxvaDF",
	"sgX0ja1bfIVQEfVZB92eK4foF/qsLLAHqC3SM3qLdFnXFH2GtYpz20Eta1VhLUuWDeTB9UpEy2IlpmUl",
	"BV8iw0R8UeiCtazJA2sLd+waURr0YamvQs9HoaySIOLgbGdnrIC9xskXMeGqIkhNSnFmitg5Wo2v1quI",
	"2EWQupSsygmZ95Qaz77vEPHVqPX0Y+eBcNNXSAe4aMPNp2mFcEAcJYnFWQa8RKpQYE4Si8yJNaHCS5fI",
	"zsPAPhI5bYWIPsv1Wgmen1fFFReVJXfv4S1swZRLtmD217D3vWRW8U353E3ygJ5NTB857Xq240v5zZtl",
	"RZYoICKggUzdNuTi0roQTIjyIYxBPpNVSryzu+oQxjaRASQAzbk5BxKw5vM+MgziJmyYww+19vMvHFyH",
	"8UY82xpVB1RXjvMvx3nrOMnimWi+tQo9QiU8jsk1mIIfhvuB5DAf4Q2F2smUsT6tyqS1TKoEIqoTK10z",
	"aa+E3s2xgapjn+UMajZUVXqD/TuSrYPES/1nRstFzeC7Jc0HGj75giNZSL7QsAzVJTZNmwYbaxYyNKgu",
	"TSTbRn5fNnWtO2S+KFpxGcWjncsmj9WEOkLE2V0jLhVZUqFXa5iSiP5S3NS9nDQtW61df6OF+2lmLR3F",
	"E1wrW+0eeCRZxX7EwMDyo/CRRx4pOSp8hDZ+6nvhCZDKzIBZs46WWFPwJVZsqAIJnGH1ArHtjAzWGys6",
	"3WwNcNZezPRLpFbI54ZuQY5SEVN5Lgr+TRxuI5mamHmAsBF9ZRf+OBJwhavVNo5JsKKOzVzBvAamwKMP",
	"JG4fd0ioOpE/AEajUTuv5W8Ie9tQnhKjwWRxNRqcLqZXo8FL+vNV9afo5IjCtb+607abjyTutv7AWDvL",
	"iZqshqMO2S3KYO6dCbl1N9GaArZxMI3ibTaCd9dTeawor07Hk1Pe57/V+xEJrGKS7RZqXxEOLhkGKX3K",
	"a9fwqgRuBzfhIH9YytrRjeOFcUKoi1v3ZgVXbM+2kwbV4EenAcsCkqRt+Tt50ZU+tXypWyFcRZQt5Dby",
	"4wcNRFS+m2GvpVKySXqe55XXOjsJbPwAM+Zxubobx+7dvlb4R1abXHKSuum2r1ImA5dsdkSd9DDeazQX",
	"+9edjf1TmnFAMT4Swsj3KIisGB7z9tJN3d4x4YruTgJrP/hHZ1zUDEQThHQvNaOYxllMdWwx3izzoyzH",
	"tnWhG9jM+in4FmKL3qKLp1lPnfXO+1ZN10x7hg400DSWpPRCtnG/2tFHsHxsvJZuc13tJTY9w39VF/R7",
	"a/O/09rs+4hx9seb8w27nW9X5o92yf9d5V+HNzfEsxPmr9YjfI/8jTqGulO50lhRvGed7FtQUDMNy2NQ",
	"tZABZahn0xlNRiqcIc3Ss2u5rNpmRkHv8p+ikwvFcRgfWQOK8Qd3CXh5zADFI6nr178Rmoxe/PkYIUXS",
	"PlAqpn66/lVmisY8hdjSBU0zRDmgFk3NEVG69uMk5Zyyjf26O0bc3OuXJ5/SNEqmjjN0nOHTJyfPXj99",
	"4jjDMCLBwA+SbewGK+I4w7yrTBxn+MVxvOcZ6uTZ09fCe9va/U4UCcjt96FIFJMv34UiCVlffweK1LZK",
	"ppVwH3Dl4Vt/EDlufhA57vtB5Kngg8jTb/NB5IwcfQtIw9Rdz92b/KQpkscP0tPJ3gQ/SMkNq88Zg0FW",
	"Yez1Y6kZwPFL1fVFFhW3wrK41Ro7+rh/n8Ck7LJdUfQGpx2zha++V+a6CSK6k4AfXIdgGmzXawnQ/eZG",
	"PpiC05PRyQhk+fQpM6bcesMvk/J35oaQHcTUGezy5YEpf5W8nOxL0lno3eWfVKfF3omidZ57w8/5oH7/",
	"1XRrtyW+sO52zAMsYJmWk9H4v7dqYxSxY3+S2EvD+3JgsmNj9zVhVzPeZ0r2vOqz6lfoV2Kl9pDhfiyz",
	"WzTMf9Ec+J+wBLghovg9jBajhw/CbvefAAAA//+nXA4SzC8AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
