openapi: 3.0.0
paths:
  /consents/v2/consents:
    post:
      operationId: CreateConsentV2
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateConsentRequestV2'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConsentResponseV2'
  /consents/v2/consents/{consentId}:
    get:
      operationId: ConsentV2
      parameters:
          - $ref: '#/components/parameters/consentId'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConsentResponseV2'
    delete:
      operationId: DeleteConsentV2
      parameters:
        - $ref: '#/components/parameters/consentId'
      responses:
        '204':
          description: .
components:
  schemas:
    ResponseError:
      type: object
      required:
        - errors
      properties:
        errors:
          type: array
          minItems: 1
          maxItems: 13
          items:
            $ref: '#/components/schemas/Error'
        meta:
          $ref: '#/components/schemas/Meta'
    Error:
      type: object
      required:
        - code
        - title
        - detail
        - requestDateTime
      properties:
        code:
          type: string
          pattern: '[\w\W\s]*'
          maxLength: 255
        title:
          type: string
          pattern: '[\w\W\s]*'
          maxLength: 255
        detail:
          type: string
          pattern: '[\w\W\s]*'
          maxLength: 2048
        requestDateTime:
          type: string
          maxLength: 20
          format: date-time
      additionalProperties: false
    Links:
      type: object
      required:
        - self
      properties:
        self:
          type: string
          format: uri
          maxLength: 2000
          pattern: ^(https:\/\/)(.*?)(\/open-insurance\/consents\/v\d+)(\/.*)?$
        first:
          type: string
          format: uri
          maxLength: 2000
          pattern: ^(https:\/\/)(.*?)(\/open-insurance\/consents\/v\d+)(\/.*)?$
        prev:
          type: string
          format: uri
          maxLength: 2000
          pattern: ^(https:\/\/)(.*?)(\/open-insurance\/consents\/v\d+)(\/.*)?$
        next:
          type: string
          format: uri
          maxLength: 2000
          pattern: ^(https:\/\/)(.*?)(\/open-insurance\/consents\/v\d+)(\/.*)?$
        last:
          type: string
          format: uri
          maxLength: 2000
          pattern: ^(https:\/\/)(.*?)(\/open-insurance\/consents\/v\d+)(\/.*)?$
      additionalProperties: false
    Meta:
      type: object
      required:
        - totalRecords
        - totalPages
      properties:
        totalRecords:
          type: integer
          format: int32
        totalPages:
          type: integer
          format: int32
      additionalProperties: false
    LoggedUser:
      type: object
      additionalProperties: false
      required:
        - document
      properties:
        document:
          type: object
          additionalProperties: false
          required:
            - identification
            - rel
          properties:
            identification:
              type: string
              maxLength: 11
              pattern: '^\d{11}$'
            rel:
              type: string
              maxLength: 3
              pattern: '^[A-Z]{3}$'
    BusinessEntity:
      type: object
      additionalProperties: false
      required:
        - document
      properties:
        document:
          type: object
          additionalProperties: false
          required:
            - identification
            - rel
          properties:
            identification:
              type: string
              maxLength: 14
              pattern: '^\d{14}$'
            rel:
              type: string
              maxLength: 4
              pattern: '^[A-Z]{4}$'
    CreateConsentRequestV2:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - permissions
            - loggedUser
            - expirationDateTime
          properties:
            loggedUser:
              $ref: '#/components/schemas/LoggedUser'
            businessEntity:
              $ref: '#/components/schemas/BusinessEntity'
            permissions:
              type: array
              items:
                $ref: '#/components/schemas/ConsentPermission'
              minItems: 1
            expirationDateTime:
              type: string
              maxLength: 20
              format: date-time
            endorsementInformation:
              type: object
              required:
                - policyNumber
                - endorsementType
                - requestDescription
              properties:
                policyNumber:
                  type: string
                  maxLength: 60
                  example: "111111"
                endorsementType:
                  $ref: '#/components/schemas/EndorsementType'
                requestDescription:
                  type: string
                  maxLength: 1024
            claimNotificationInformation:
              type: object
              required:
                - documentType
                - policyNumber
                - occurrenceDate
                - occurrenceDescription
              properties:
                documentType:
                  type: string
                  enum: [APOLICE_INDIVIDUAL,
                         BILHETE,
                         CERTIFICADO,
                         APOLICE_INDIVIDUAL_AUTOMOVEL,
                         APOLICE_FROTA_AUTOMOVEL,
                         CERTIFICADO_AUTOMOVEL]
                policyNumber:
                  type: string
                  maxLength: 60
                  example: "111111"
                groupCertificateId:
                  type: string
                  maxLength: 60
                occurrenceDate:
                  type: string
                  format: date
                  maxLength: 10
                occurrenceTime:
                  type: string
                  pattern: '[0-2][0-3]:[0-5][0-9]:[0-5][0-9]'
                occurrenceDescription:
                  type: string
                  maxLength: 10000
          additionalProperties: false
      additionalProperties: false
    ConsentResponseV2:
      type: object
      required:
        - data
      properties:
        data:
          $ref: '#/components/schemas/ConsentResponseDataV2'
        links:
          $ref: '#/components/schemas/Links'
        meta:
          $ref: '#/components/schemas/Meta'
      additionalProperties: false
    ConsentResponseDataV2:
      type: object
      required:
        - consentId
        - creationDateTime
        - status
        - statusUpdateDateTime
        - permissions
        - expirationDateTime
      properties:
        consentId:
          type: string
          pattern: '^urn:[a-zA-Z0-9][a-zA-Z0-9-]{0,31}:[a-zA-Z0-9()+,\-.:=@;$_!*''%\/?#]+$'
          maxLength: 256
          example: 'urn:prudential:C1DD93123'
        creationDateTime:
          type: string
          format: date-time
          maxLength: 20
        status:
          $ref: '#/components/schemas/ConsentStatus'
        statusUpdateDateTime:
          type: string
          format: date-time
          maxLength: 20
        permissions:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/ConsentPermission'
        expirationDateTime:
          type: string
          format: date-time
          maxLength: 20
        endorsementInformation:
          type: object
          required:
            - policyNumber
            - endorsementType
            - requestDescription
          properties:
            policyNumber:
              type: string
              maxLength: 60
            endorsementType:
              $ref: '#/components/schemas/EndorsementType'
            requestDescription:
              type: string
              maxLength: 1024
        claimNotificationInformation:
          type: object
          required:
            - documentType
            - policyNumber
            - occurrenceDate
            - occurrenceDescription
          properties:
            documentType:
              description: Tipo de Documento Emitido.
              type: string
              enum: [APOLICE_INDIVIDUAL,
                      BILHETE,
                      CERTIFICADO,
                      APOLICE_INDIVIDUAL_AUTOMOVEL,
                      APOLICE_FROTA_AUTOMOVEL,
                      CERTIFICADO_AUTOMOVEL]
            policyNumber:
              type: string
              maxLength: 60
            groupCertificateId:
              type: string
              maxLength: 60
            occurrenceDate:
              type: string
              format: date
              maxLength: 10
            occurrenceTime:
              type: string
              pattern: '[0-2][0-3]:[0-5][0-9]:[0-5][0-9]'
            occurrenceDescription:
              type: string
              maxLength: 10000
        rejection:
          $ref: '#/components/schemas/ConsentRejection'
    ConsentStatus:
      type: string
      enum:
        - AUTHORISED
        - AWAITING_AUTHORISATION
        - REJECTED
        - CONSUMED
    ConsentPermission:
      type: string
      enum:
        - CUSTOMERS_PERSONAL_IDENTIFICATIONS_READ
        - CUSTOMERS_PERSONAL_ADDITIONALINFO_READ
        - CUSTOMERS_PERSONAL_QUALIFICATION_READ
        - CUSTOMERS_BUSINESS_IDENTIFICATIONS_READ
        - CUSTOMERS_BUSINESS_QUALIFICATION_READ
        - CUSTOMERS_BUSINESS_ADDITIONALINFO_READ
        - CAPITALIZATION_TITLE_READ
        - CAPITALIZATION_TITLE_PLANINFO_READ
        - CAPITALIZATION_TITLE_EVENTS_READ
        - CAPITALIZATION_TITLE_SETTLEMENTS_READ
        - PENSION_PLAN_READ
        - PENSION_PLAN_CONTRACTINFO_READ
        - PENSION_PLAN_MOVEMENTS_READ
        - PENSION_PLAN_PORTABILITIES_READ
        - PENSION_PLAN_WITHDRAWALS_READ
        - PENSION_PLAN_CLAIM
        - LIFE_PENSION_READ
        - LIFE_PENSION_CONTRACTINFO_READ
        - LIFE_PENSION_MOVEMENTS_READ
        - LIFE_PENSION_PORTABILITIES_READ
        - LIFE_PENSION_WITHDRAWALS_READ
        - LIFE_PENSION_CLAIM
        - FINANCIAL_ASSISTANCE_READ
        - FINANCIAL_ASSISTANCE_CONTRACTINFO_READ
        - FINANCIAL_ASSISTANCE_MOVEMENTS_READ
        - DAMAGES_AND_PEOPLE_PATRIMONIAL_READ
        - DAMAGES_AND_PEOPLE_PATRIMONIAL_POLICYINFO_READ
        - DAMAGES_AND_PEOPLE_PATRIMONIAL_PREMIUM_READ
        - DAMAGES_AND_PEOPLE_PATRIMONIAL_CLAIM_READ
        - DAMAGES_AND_PEOPLE_RESPONSIBILITY_READ
        - DAMAGES_AND_PEOPLE_RESPONSIBILITY_POLICYINFO_READ
        - DAMAGES_AND_PEOPLE_RESPONSIBILITY_PREMIUM_READ
        - DAMAGES_AND_PEOPLE_RESPONSIBILITY_CLAIM_READ
        - DAMAGES_AND_PEOPLE_TRANSPORT_READ
        - DAMAGES_AND_PEOPLE_TRANSPORT_POLICYINFO_READ
        - DAMAGES_AND_PEOPLE_TRANSPORT_PREMIUM_READ
        - DAMAGES_AND_PEOPLE_TRANSPORT_CLAIM_READ
        - DAMAGES_AND_PEOPLE_FINANCIAL_RISKS_READ
        - DAMAGES_AND_PEOPLE_FINANCIAL_RISKS_POLICYINFO_READ
        - DAMAGES_AND_PEOPLE_FINANCIAL_RISKS_PREMIUM_READ
        - DAMAGES_AND_PEOPLE_FINANCIAL_RISKS_CLAIM_READ
        - DAMAGES_AND_PEOPLE_RURAL_READ
        - DAMAGES_AND_PEOPLE_RURAL_POLICYINFO_READ
        - DAMAGES_AND_PEOPLE_RURAL_PREMIUM_READ
        - DAMAGES_AND_PEOPLE_RURAL_CLAIM_READ
        - DAMAGES_AND_PEOPLE_AUTO_READ
        - DAMAGES_AND_PEOPLE_AUTO_POLICYINFO_READ
        - DAMAGES_AND_PEOPLE_AUTO_PREMIUM_READ
        - DAMAGES_AND_PEOPLE_AUTO_CLAIM_READ
        - DAMAGES_AND_PEOPLE_HOUSING_READ
        - DAMAGES_AND_PEOPLE_HOUSING_POLICYINFO_READ
        - DAMAGES_AND_PEOPLE_HOUSING_PREMIUM_READ
        - DAMAGES_AND_PEOPLE_HOUSING_CLAIM_READ
        - DAMAGES_AND_PEOPLE_ACCEPTANCE_AND_BRANCHES_ABROAD_READ
        - DAMAGES_AND_PEOPLE_ACCEPTANCE_AND_BRANCHES_ABROAD_POLICYINFO_READ
        - DAMAGES_AND_PEOPLE_ACCEPTANCE_AND_BRANCHES_ABROAD_PREMIUM_READ
        - DAMAGES_AND_PEOPLE_ACCEPTANCE_AND_BRANCHES_ABROAD_CLAIM_READ
        - DAMAGES_AND_PEOPLE_PERSON_READ
        - DAMAGES_AND_PEOPLE_PERSON_POLICYINFO_READ
        - DAMAGES_AND_PEOPLE_PERSON_PREMIUM_READ
        - DAMAGES_AND_PEOPLE_PERSON_CLAIM_READ
        - ENDORSEMENT_REQUEST_CREATE
        - CLAIM_NOTIFICATION_REQUEST_DAMAGE_CREATE
        - CLAIM_NOTIFICATION_REQUEST_PERSON_CREATE
        - QUOTE_PATRIMONIAL_LEAD_CREATE
        - QUOTE_PATRIMONIAL_LEAD_UPDATE
        - QUOTE_PATRIMONIAL_HOME_READ
        - QUOTE_PATRIMONIAL_HOME_CREATE
        - QUOTE_PATRIMONIAL_HOME_UPDATE
        - QUOTE_PATRIMONIAL_CONDOMINIUM_READ
        - QUOTE_PATRIMONIAL_CONDOMINIUM_CREATE
        - QUOTE_PATRIMONIAL_CONDOMINIUM_UPDATE
        - QUOTE_PATRIMONIAL_BUSINESS_READ
        - QUOTE_PATRIMONIAL_BUSINESS_CREATE
        - QUOTE_PATRIMONIAL_BUSINESS_UPDATE
        - QUOTE_PATRIMONIAL_DIVERSE_RISKS_READ
        - QUOTE_PATRIMONIAL_DIVERSE_RISKS_CREATE
        - QUOTE_PATRIMONIAL_DIVERSE_RISKS_UPDATE
        - QUOTE_ACCEPTANCE_AND_BRANCHES_ABROAD_LEAD_CREATE
        - QUOTE_ACCEPTANCE_AND_BRANCHES_ABROAD_LEAD_UPDATE
        - QUOTE_AUTO_LEAD_CREATE
        - QUOTE_AUTO_LEAD_UPDATE
        - QUOTE_AUTO_READ
        - QUOTE_AUTO_CREATE
        - QUOTE_AUTO_UPDATE
        - QUOTE_FINANCIAL_RISK_LEAD_CREATE
        - QUOTE_FINANCIAL_RISK_LEAD_UPDATE
        - QUOTE_HOUSING_LEAD_CREATE
        - QUOTE_HOUSING_LEAD_UPDATE
        - QUOTE_RESPONSIBILITY_LEAD_CREATE
        - QUOTE_RESPONSIBILITY_LEAD_UPDATE
        - QUOTE_RURAL_LEAD_CREATE
        - QUOTE_RURAL_LEAD_UPDATE
        - QUOTE_TRANSPORT_LEAD_CREATE
        - QUOTE_TRANSPORT_LEAD_UPDATE
        - QUOTE_PERSON_LEAD_CREATE
        - QUOTE_PERSON_LEAD_UPDATE
        - QUOTE_PERSON_LIFE_READ
        - QUOTE_PERSON_LIFE_CREATE
        - QUOTE_PERSON_LIFE_UPDATE
        - QUOTE_PERSON_TRAVEL_READ
        - QUOTE_PERSON_TRAVEL_CREATE
        - QUOTE_PERSON_TRAVEL_UPDATE
        - QUOTE_CAPITALIZATION_TITLE_LEAD_CREATE
        - QUOTE_CAPITALIZATION_TITLE_LEAD_UPDATE
        - QUOTE_CAPITALIZATION_TITLE_READ
        - QUOTE_CAPITALIZATION_TITLE_CREATE
        - QUOTE_CAPITALIZATION_TITLE_UPDATE
        - QUOTE_CAPITALIZATION_TITLE_RAFFLE_CREATE
        - CONTRACT_LIFE_PENSION_LEAD_CREATE
        - CONTRACT_LIFE_PENSION_LEAD_UPDATE
        - CONTRACT_LIFE_PENSION_LEAD_PORTABILITY_CREATE
        - CONTRACT_LIFE_PENSION_LEAD_PORTABILITY_UPDATE
        - CONTRACT_PENSION_PLAN_LEAD_CREATE
        - CONTRACT_PENSION_PLAN_LEAD_UPDATE
        - CONTRACT_PENSION_PLAN_LEAD_PORTABILITY_CREATE
        - CONTRACT_PENSION_PLAN_LEAD_PORTABILITY_UPDATE
        - PENSION_WITHDRAWAL_CREATE
        - CAPITALIZATION_TITLE_WITHDRAWAL_CREATE
        - RESOURCES_READ
    EndorsementType:
      type: string
      enum:
        - ALTERACAO
        - CANCELAMENTO
        - INCLUSAO
        - EXCLUSAO
    ConsentRejection:
      type: object
      required:
        - rejectedBy
        - reason
      properties:
        rejectedBy:
          $ref: '#/components/schemas/ConsentRejectedBy'
        reason:
          $ref: '#/components/schemas/ConsentRejectedReason'
    ConsentRejectedBy:
      type: string
      enum:
        - USER
        - ASPSP
        - TPP
    ConsentRejectedReason:
      type: object
      required:
        - code
      properties:
        code:
          $ref: '#/components/schemas/ConsentRejectedReasonCode'
        additionalInformation:
          type: string
          maxLength: 140
          pattern: '[\w\W\s]*'
    ConsentRejectedReasonCode:
      type: string
      enum:
        - CONSENT_EXPIRED
        - CUSTOMER_MANUALLY_REJECTED
        - CUSTOMER_MANUALLY_REVOKED
        - CONSENT_MAX_DATE_REACHED
        - CONSENT_TECHNICAL_ISSUE
        - INTERNAL_SECURITY_REASON
  parameters:
    consentId:
      name: consentId
      in: path
      required: true
      schema:
        type: string
        pattern: '^urn:[a-zA-Z0-9][a-zA-Z0-9-]{0,31}:[a-zA-Z0-9()+,\-.:=@;$_!*''%\/?#]+$'
        maxLength: 256