package consent

import (
	"slices"

	"github.com/luikyv/go-open-insurance/internal/api"
)

var permissionsPhase2 = []api.ConsentPermission{
	api.ConsentPermissionRESOURCESREAD,
	api.ConsentPermissionCUSTOMERSPERSONALIDENTIFICATIONSREAD,
	api.ConsentPermissionCUSTOMERSPERSONALQUALIFICATIONREAD,
	api.ConsentPermissionCUSTOMERSPERSONALADDITIONALINFOREAD,
	api.ConsentPermissionCUSTOMERSBUSINESSIDENTIFICATIONSREAD,
	api.ConsentPermissionCUSTOMERSBUSINESSQUALIFICATIONREAD,
	api.ConsentPermissionCUSTOMERSBUSINESSADDITIONALINFOREAD,
	api.ConsentPermissionCAPITALIZATIONTITLEREAD,
	api.ConsentPermissionCAPITALIZATIONTITLEPLANINFOREAD,
	api.ConsentPermissionCAPITALIZATIONTITLEEVENTSREAD,
	api.ConsentPermissionCAPITALIZATIONTITLESETTLEMENTSREAD,
	api.ConsentPermissionPENSIONPLANREAD,
	api.ConsentPermissionPENSIONPLANCONTRACTINFOREAD,
	api.ConsentPermissionPENSIONPLANMOVEMENTSREAD,
	api.ConsentPermissionPENSIONPLANPORTABILITIESREAD,
	api.ConsentPermissionPENSIONPLANWITHDRAWALSREAD,
	api.ConsentPermissionPENSIONPLANCLAIM,
	api.ConsentPermissionLIFEPENSIONREAD,
	api.ConsentPermissionLIFEPENSIONCONTRACTINFOREAD,
	api.ConsentPermissionLIFEPENSIONMOVEMENTSREAD,
	api.ConsentPermissionLIFEPENSIONPORTABILITIESREAD,
	api.ConsentPermissionLIFEPENSIONWITHDRAWALSREAD,
	api.ConsentPermissionLIFEPENSIONCLAIM,
	api.ConsentPermissionFINANCIALASSISTANCEREAD,
	api.ConsentPermissionFINANCIALASSISTANCECONTRACTINFOREAD,
	api.ConsentPermissionFINANCIALASSISTANCEMOVEMENTSREAD,
	api.ConsentPermissionDAMAGESANDPEOPLEPATRIMONIALREAD,
	api.ConsentPermissionDAMAGESANDPEOPLEPATRIMONIALPOLICYINFOREAD,
	api.ConsentPermissionDAMAGESANDPEOPLEPATRIMONIALPREMIUMREAD,
	api.ConsentPermissionDAMAGESANDPEOPLEPATRIMONIALCLAIMREAD,
	api.ConsentPermissionDAMAGESANDPEOPLERESPONSIBILITYREAD,
	api.ConsentPermissionDAMAGESANDPEOPLERESPONSIBILITYPOLICYINFOREAD,
	api.ConsentPermissionDAMAGESANDPEOPLERESPONSIBILITYPREMIUMREAD,
	api.ConsentPermissionDAMAGESANDPEOPLERESPONSIBILITYCLAIMREAD,
	api.ConsentPermissionDAMAGESANDPEOPLETRANSPORTREAD,
	api.ConsentPermissionDAMAGESANDPEOPLETRANSPORTPOLICYINFOREAD,
	api.ConsentPermissionDAMAGESANDPEOPLETRANSPORTPREMIUMREAD,
	api.ConsentPermissionDAMAGESANDPEOPLETRANSPORTCLAIMREAD,
	api.ConsentPermissionDAMAGESANDPEOPLEFINANCIALRISKSREAD,
	api.ConsentPermissionDAMAGESANDPEOPLEFINANCIALRISKSPOLICYINFOREAD,
	api.ConsentPermissionDAMAGESANDPEOPLEFINANCIALRISKSPREMIUMREAD,
	api.ConsentPermissionDAMAGESANDPEOPLEFINANCIALRISKSCLAIMREAD,
	api.ConsentPermissionDAMAGESANDPEOPLERURALREAD,
	api.ConsentPermissionDAMAGESANDPEOPLERURALPOLICYINFOREAD,
	api.ConsentPermissionDAMAGESANDPEOPLERURALPREMIUMREAD,
	api.ConsentPermissionDAMAGESANDPEOPLERURALCLAIMREAD,
	api.ConsentPermissionDAMAGESANDPEOPLEAUTOREAD,
	api.ConsentPermissionDAMAGESANDPEOPLEAUTOPOLICYINFOREAD,
	api.ConsentPermissionDAMAGESANDPEOPLEAUTOPREMIUMREAD,
	api.ConsentPermissionDAMAGESANDPEOPLEAUTOCLAIMREAD,
	api.ConsentPermissionDAMAGESANDPEOPLEHOUSINGREAD,
	api.ConsentPermissionDAMAGESANDPEOPLEHOUSINGPOLICYINFOREAD,
	api.ConsentPermissionDAMAGESANDPEOPLEHOUSINGPREMIUMREAD,
	api.ConsentPermissionDAMAGESANDPEOPLEHOUSINGCLAIMREAD,
	api.ConsentPermissionDAMAGESANDPEOPLEACCEPTANCEANDBRANCHESABROADREAD,
	api.ConsentPermissionDAMAGESANDPEOPLEACCEPTANCEANDBRANCHESABROADPOLICYINFOREAD,
	api.ConsentPermissionDAMAGESANDPEOPLEACCEPTANCEANDBRANCHESABROADPREMIUMREAD,
	api.ConsentPermissionDAMAGESANDPEOPLEACCEPTANCEANDBRANCHESABROADCLAIMREAD,
	api.ConsentPermissionDAMAGESANDPEOPLEPERSONREAD,
	api.ConsentPermissionDAMAGESANDPEOPLEPERSONPOLICYINFOREAD,
	api.ConsentPermissionDAMAGESANDPEOPLEPERSONPREMIUMREAD,
	api.ConsentPermissionDAMAGESANDPEOPLEPERSONCLAIMREAD,
}

var permissionsPhase3 = []api.ConsentPermission{
	api.ConsentPermissionCLAIMNOTIFICATIONREQUESTDAMAGECREATE,
	api.ConsentPermissionCLAIMNOTIFICATIONREQUESTPERSONCREATE,
	api.ConsentPermissionENDORSEMENTREQUESTCREATE,
	api.ConsentPermissionQUOTEPATRIMONIALLEADCREATE,
	api.ConsentPermissionQUOTEPATRIMONIALLEADUPDATE,
	api.ConsentPermissionQUOTEPATRIMONIALHOMEREAD,
	api.ConsentPermissionQUOTEPATRIMONIALHOMECREATE,
	api.ConsentPermissionQUOTEPATRIMONIALHOMEUPDATE,
	api.ConsentPermissionQUOTEPATRIMONIALCONDOMINIUMREAD,
	api.ConsentPermissionQUOTEPATRIMONIALCONDOMINIUMCREATE,
	api.ConsentPermissionQUOTEPATRIMONIALCONDOMINIUMUPDATE,
	api.ConsentPermissionQUOTEPATRIMONIALBUSINESSREAD,
	api.ConsentPermissionQUOTEPATRIMONIALBUSINESSCREATE,
	api.ConsentPermissionQUOTEPATRIMONIALBUSINESSUPDATE,
	api.ConsentPermissionQUOTEPATRIMONIALDIVERSERISKSREAD,
	api.ConsentPermissionQUOTEPATRIMONIALDIVERSERISKSCREATE,
	api.ConsentPermissionQUOTEPATRIMONIALDIVERSERISKSUPDATE,
	api.ConsentPermissionQUOTEACCEPTANCEANDBRANCHESABROADLEADCREATE,
	api.ConsentPermissionQUOTEACCEPTANCEANDBRANCHESABROADLEADUPDATE,
	api.ConsentPermissionQUOTEAUTOLEADCREATE,
	api.ConsentPermissionQUOTEAUTOLEADUPDATE,
	api.ConsentPermissionQUOTEAUTOREAD,
	api.ConsentPermissionQUOTEAUTOCREATE,
	api.ConsentPermissionQUOTEAUTOUPDATE,
	api.ConsentPermissionQUOTEFINANCIALRISKLEADCREATE,
	api.ConsentPermissionQUOTEFINANCIALRISKLEADUPDATE,
	api.ConsentPermissionQUOTEHOUSINGLEADCREATE,
	api.ConsentPermissionQUOTEHOUSINGLEADUPDATE,
	api.ConsentPermissionQUOTERESPONSIBILITYLEADCREATE,
	api.ConsentPermissionQUOTERESPONSIBILITYLEADUPDATE,
	api.ConsentPermissionQUOTERURALLEADCREATE,
	api.ConsentPermissionQUOTERURALLEADUPDATE,
	api.ConsentPermissionQUOTETRANSPORTLEADCREATE,
	api.ConsentPermissionQUOTETRANSPORTLEADUPDATE,
	api.ConsentPermissionQUOTEPERSONLEADCREATE,
	api.ConsentPermissionQUOTEPERSONLEADUPDATE,
	api.ConsentPermissionQUOTEPERSONLIFEREAD,
	api.ConsentPermissionQUOTEPERSONLIFECREATE,
	api.ConsentPermissionQUOTEPERSONLIFEUPDATE,
	api.ConsentPermissionQUOTEPERSONTRAVELREAD,
	api.ConsentPermissionQUOTEPERSONTRAVELCREATE,
	api.ConsentPermissionQUOTEPERSONTRAVELUPDATE,
	api.ConsentPermissionQUOTECAPITALIZATIONTITLELEADCREATE,
	api.ConsentPermissionQUOTECAPITALIZATIONTITLELEADUPDATE,
	api.ConsentPermissionQUOTECAPITALIZATIONTITLEREAD,
	api.ConsentPermissionQUOTECAPITALIZATIONTITLECREATE,
	api.ConsentPermissionQUOTECAPITALIZATIONTITLEUPDATE,
	api.ConsentPermissionQUOTECAPITALIZATIONTITLERAFFLECREATE,
	api.ConsentPermissionCONTRACTPENSIONPLANLEADCREATE,
	api.ConsentPermissionCONTRACTPENSIONPLANLEADUPDATE,
	api.ConsentPermissionCONTRACTPENSIONPLANLEADPORTABILITYCREATE,
	api.ConsentPermissionCONTRACTPENSIONPLANLEADPORTABILITYUPDATE,
	api.ConsentPermissionCONTRACTLIFEPENSIONLEADCREATE,
	api.ConsentPermissionCONTRACTLIFEPENSIONLEADUPDATE,
	api.ConsentPermissionCONTRACTLIFEPENSIONLEADPORTABILITYCREATE,
	api.ConsentPermissionCONTRACTLIFEPENSIONLEADPORTABILITYUPDATE,
	api.ConsentPermissionPENSIONWITHDRAWALCREATE,
	api.ConsentPermissionCAPITALIZATIONTITLEWITHDRAWALCREATE,
}

var (
	permissionCategoryPersonalRegistration PermissionCategory = []api.ConsentPermission{
		api.ConsentPermissionRESOURCESREAD,
		api.ConsentPermissionCUSTOMERSPERSONALIDENTIFICATIONSREAD,
		api.ConsentPermissionCUSTOMERSPERSONALQUALIFICATIONREAD,
		api.ConsentPermissionCUSTOMERSPERSONALADDITIONALINFOREAD,
	}
	permissionCategoryBusinessRegistration PermissionCategory = []api.ConsentPermission{
		api.ConsentPermissionRESOURCESREAD,
		api.ConsentPermissionCUSTOMERSBUSINESSIDENTIFICATIONSREAD,
		api.ConsentPermissionCUSTOMERSBUSINESSQUALIFICATIONREAD,
		api.ConsentPermissionCUSTOMERSBUSINESSADDITIONALINFOREAD,
	}
	permissionCategoryCapitalizationTitle PermissionCategory = []api.ConsentPermission{
		api.ConsentPermissionRESOURCESREAD,
		api.ConsentPermissionCAPITALIZATIONTITLEREAD,
		api.ConsentPermissionCAPITALIZATIONTITLEPLANINFOREAD,
		api.ConsentPermissionCAPITALIZATIONTITLEEVENTSREAD,
		api.ConsentPermissionCAPITALIZATIONTITLESETTLEMENTSREAD,
	}
	permissionCategoryPensionPlan PermissionCategory = []api.ConsentPermission{
		api.ConsentPermissionRESOURCESREAD,
		api.ConsentPermissionPENSIONPLANREAD,
		api.ConsentPermissionPENSIONPLANCONTRACTINFOREAD,
		api.ConsentPermissionPENSIONPLANMOVEMENTSREAD,
		api.ConsentPermissionPENSIONPLANPORTABILITIESREAD,
		api.ConsentPermissionPENSIONPLANWITHDRAWALSREAD,
		api.ConsentPermissionPENSIONPLANCLAIM,
	}
	permissionCategoryLifePensionPlan PermissionCategory = []api.ConsentPermission{
		api.ConsentPermissionRESOURCESREAD,
		api.ConsentPermissionLIFEPENSIONREAD,
		api.ConsentPermissionLIFEPENSIONCONTRACTINFOREAD,
		api.ConsentPermissionLIFEPENSIONMOVEMENTSREAD,
		api.ConsentPermissionLIFEPENSIONPORTABILITIESREAD,
		api.ConsentPermissionLIFEPENSIONWITHDRAWALSREAD,
		api.ConsentPermissionLIFEPENSIONCLAIM,
	}
	permissionCategoryFinancialAssistence PermissionCategory = []api.ConsentPermission{
		api.ConsentPermissionFINANCIALASSISTANCEREAD,
		api.ConsentPermissionFINANCIALASSISTANCECONTRACTINFOREAD,
		api.ConsentPermissionFINANCIALASSISTANCEMOVEMENTSREAD,
	}
	permissionCategoryDamagesAndPeoplePatrimonial PermissionCategory = []api.ConsentPermission{
		api.ConsentPermissionRESOURCESREAD,
		api.ConsentPermissionDAMAGESANDPEOPLEPATRIMONIALREAD,
		api.ConsentPermissionDAMAGESANDPEOPLEPATRIMONIALPOLICYINFOREAD,
		api.ConsentPermissionDAMAGESANDPEOPLEPATRIMONIALPREMIUMREAD,
		api.ConsentPermissionDAMAGESANDPEOPLEPATRIMONIALCLAIMREAD,
	}
	permissionCategoryDamagesAndPeopleResponsibility PermissionCategory = []api.ConsentPermission{
		api.ConsentPermissionRESOURCESREAD,
		api.ConsentPermissionDAMAGESANDPEOPLERESPONSIBILITYREAD,
		api.ConsentPermissionDAMAGESANDPEOPLERESPONSIBILITYPOLICYINFOREAD,
		api.ConsentPermissionDAMAGESANDPEOPLERESPONSIBILITYPREMIUMREAD,
		api.ConsentPermissionDAMAGESANDPEOPLERESPONSIBILITYCLAIMREAD,
	}
	permissionCategoryDamagesAndPeopleTransport PermissionCategory = []api.ConsentPermission{
		api.ConsentPermissionRESOURCESREAD,
		api.ConsentPermissionDAMAGESANDPEOPLETRANSPORTREAD,
		api.ConsentPermissionDAMAGESANDPEOPLETRANSPORTPOLICYINFOREAD,
		api.ConsentPermissionDAMAGESANDPEOPLETRANSPORTPREMIUMREAD,
		api.ConsentPermissionDAMAGESANDPEOPLETRANSPORTCLAIMREAD,
	}
	permissionCategoryDamagesAndPeopleFinancialRisks PermissionCategory = []api.ConsentPermission{
		api.ConsentPermissionRESOURCESREAD,
		api.ConsentPermissionDAMAGESANDPEOPLEFINANCIALRISKSREAD,
		api.ConsentPermissionDAMAGESANDPEOPLEFINANCIALRISKSPOLICYINFOREAD,
		api.ConsentPermissionDAMAGESANDPEOPLEFINANCIALRISKSPREMIUMREAD,
		api.ConsentPermissionDAMAGESANDPEOPLEFINANCIALRISKSCLAIMREAD,
	}
	permissionCategoryDamagesAndPeopleRural PermissionCategory = []api.ConsentPermission{
		api.ConsentPermissionRESOURCESREAD,
		api.ConsentPermissionDAMAGESANDPEOPLERURALREAD,
		api.ConsentPermissionDAMAGESANDPEOPLERURALPOLICYINFOREAD,
		api.ConsentPermissionDAMAGESANDPEOPLERURALPREMIUMREAD,
		api.ConsentPermissionDAMAGESANDPEOPLERURALCLAIMREAD,
	}
	permissionCategoryDamagesAndPeopleAuto PermissionCategory = []api.ConsentPermission{
		api.ConsentPermissionRESOURCESREAD,
		api.ConsentPermissionDAMAGESANDPEOPLEAUTOREAD,
		api.ConsentPermissionDAMAGESANDPEOPLEAUTOPOLICYINFOREAD,
		api.ConsentPermissionDAMAGESANDPEOPLEAUTOPREMIUMREAD,
		api.ConsentPermissionDAMAGESANDPEOPLEAUTOCLAIMREAD,
	}
	permissionCategoryDamagesAndPeopleHousing PermissionCategory = []api.ConsentPermission{
		api.ConsentPermissionRESOURCESREAD,
		api.ConsentPermissionDAMAGESANDPEOPLEHOUSINGREAD,
		api.ConsentPermissionDAMAGESANDPEOPLEHOUSINGPOLICYINFOREAD,
		api.ConsentPermissionDAMAGESANDPEOPLEHOUSINGPREMIUMREAD,
		api.ConsentPermissionDAMAGESANDPEOPLEHOUSINGCLAIMREAD,
	}
	permissionCategoryDamagesAndPeopleAcceptanceAndBranchesAbroad PermissionCategory = []api.ConsentPermission{
		api.ConsentPermissionRESOURCESREAD,
		api.ConsentPermissionDAMAGESANDPEOPLEACCEPTANCEANDBRANCHESABROADREAD,
		api.ConsentPermissionDAMAGESANDPEOPLEACCEPTANCEANDBRANCHESABROADPOLICYINFOREAD,
		api.ConsentPermissionDAMAGESANDPEOPLEACCEPTANCEANDBRANCHESABROADPREMIUMREAD,
		api.ConsentPermissionDAMAGESANDPEOPLEACCEPTANCEANDBRANCHESABROADCLAIMREAD,
	}
	permissionCategoryDamagesAndPeoplePerson PermissionCategory = []api.ConsentPermission{
		api.ConsentPermissionRESOURCESREAD,
		api.ConsentPermissionDAMAGESANDPEOPLEPERSONREAD,
		api.ConsentPermissionDAMAGESANDPEOPLEPERSONPOLICYINFOREAD,
		api.ConsentPermissionDAMAGESANDPEOPLEPERSONPREMIUMREAD,
		api.ConsentPermissionDAMAGESANDPEOPLEPERSONCLAIMREAD,
	}
	permissionCategoryClaimNotificationRequestDamage PermissionCategory = []api.ConsentPermission{
		api.ConsentPermissionCLAIMNOTIFICATIONREQUESTDAMAGECREATE,
	}
	permissionCategoryClaimNotificationRequestPerson PermissionCategory = []api.ConsentPermission{
		api.ConsentPermissionCLAIMNOTIFICATIONREQUESTPERSONCREATE,
	}
	permissionCategoryEndorsementRequest PermissionCategory = []api.ConsentPermission{
		api.ConsentPermissionENDORSEMENTREQUESTCREATE,
	}
	permissionCategoryQuotePatrimonialLead PermissionCategory = []api.ConsentPermission{
		api.ConsentPermissionQUOTEPATRIMONIALLEADCREATE,
		api.ConsentPermissionQUOTEPATRIMONIALLEADUPDATE,
	}
	permissionCategoryQuotePatrimonialHome PermissionCategory = []api.ConsentPermission{
		api.ConsentPermissionQUOTEPATRIMONIALHOMEREAD,
		api.ConsentPermissionQUOTEPATRIMONIALHOMECREATE,
		api.ConsentPermissionQUOTEPATRIMONIALHOMEUPDATE,
	}
	permissionCategoryQuotePatrimonialCondominium PermissionCategory = []api.ConsentPermission{
		api.ConsentPermissionQUOTEPATRIMONIALCONDOMINIUMREAD,
		api.ConsentPermissionQUOTEPATRIMONIALCONDOMINIUMCREATE,
		api.ConsentPermissionQUOTEPATRIMONIALCONDOMINIUMUPDATE,
	}
	permissionCategoryQuotePatrimonialBusiness PermissionCategory = []api.ConsentPermission{
		api.ConsentPermissionQUOTEPATRIMONIALBUSINESSREAD,
		api.ConsentPermissionQUOTEPATRIMONIALBUSINESSCREATE,
		api.ConsentPermissionQUOTEPATRIMONIALBUSINESSUPDATE,
	}
	permissionCategoryQuotePatrimonialDiverseRisks PermissionCategory = []api.ConsentPermission{
		api.ConsentPermissionQUOTEPATRIMONIALDIVERSERISKSREAD,
		api.ConsentPermissionQUOTEPATRIMONIALDIVERSERISKSCREATE,
		api.ConsentPermissionQUOTEPATRIMONIALDIVERSERISKSUPDATE,
	}
	permissionCategoryQuoteAcceptanceAndBranchesAbroadLead PermissionCategory = []api.ConsentPermission{
		api.ConsentPermissionQUOTEACCEPTANCEANDBRANCHESABROADLEADCREATE,
		api.ConsentPermissionQUOTEACCEPTANCEANDBRANCHESABROADLEADUPDATE,
	}
	permissionCategoryQuoteAutoLead PermissionCategory = []api.ConsentPermission{
		api.ConsentPermissionQUOTEAUTOCREATE,
		api.ConsentPermissionQUOTEAUTOUPDATE,
	}
	permissionCategoryQuoteAuto PermissionCategory = []api.ConsentPermission{
		api.ConsentPermissionQUOTEAUTOREAD,
		api.ConsentPermissionQUOTEAUTOCREATE,
		api.ConsentPermissionQUOTEAUTOUPDATE,
	}
	permissionCategoryQuoteFinancialRiskLead PermissionCategory = []api.ConsentPermission{
		api.ConsentPermissionQUOTEFINANCIALRISKLEADCREATE,
		api.ConsentPermissionQUOTEFINANCIALRISKLEADUPDATE,
	}
	permissionCategoryQuoteHousingLead PermissionCategory = []api.ConsentPermission{
		api.ConsentPermissionQUOTEHOUSINGLEADCREATE,
		api.ConsentPermissionQUOTEHOUSINGLEADUPDATE,
	}
	permissionCategoryQuoteResponsibilityLead PermissionCategory = []api.ConsentPermission{
		api.ConsentPermissionQUOTERESPONSIBILITYLEADCREATE,
		api.ConsentPermissionQUOTERESPONSIBILITYLEADUPDATE,
	}
	permissionCategoryQuoteRuralLead PermissionCategory = []api.ConsentPermission{
		api.ConsentPermissionQUOTERURALLEADCREATE,
		api.ConsentPermissionQUOTERURALLEADUPDATE,
	}
	permissionCategoryQuoteTransportLead PermissionCategory = []api.ConsentPermission{
		api.ConsentPermissionQUOTETRANSPORTLEADCREATE,
		api.ConsentPermissionQUOTETRANSPORTLEADUPDATE,
	}
	permissionCategoryQuotePersonLead PermissionCategory = []api.ConsentPermission{
		api.ConsentPermissionQUOTEPERSONLEADCREATE,
		api.ConsentPermissionQUOTEPERSONLEADUPDATE,
	}
	permissionCategoryQuotePersonLifeAuto PermissionCategory = []api.ConsentPermission{
		api.ConsentPermissionQUOTEPERSONLIFEREAD,
		api.ConsentPermissionQUOTEPERSONLIFECREATE,
		api.ConsentPermissionQUOTEPERSONLIFEUPDATE,
	}
	permissionCategoryQuoteTravelAuto PermissionCategory = []api.ConsentPermission{
		api.ConsentPermissionQUOTEPERSONTRAVELREAD,
		api.ConsentPermissionQUOTEPERSONTRAVELCREATE,
		api.ConsentPermissionQUOTEPERSONTRAVELUPDATE,
	}
	permissionCategoryQuoteCapitalizationTitleLead PermissionCategory = []api.ConsentPermission{
		api.ConsentPermissionQUOTECAPITALIZATIONTITLELEADCREATE,
		api.ConsentPermissionQUOTECAPITALIZATIONTITLELEADUPDATE,
	}
	permissionCategoryQuoteCapitalizationTitle PermissionCategory = []api.ConsentPermission{
		api.ConsentPermissionQUOTECAPITALIZATIONTITLEREAD,
		api.ConsentPermissionQUOTECAPITALIZATIONTITLECREATE,
		api.ConsentPermissionQUOTECAPITALIZATIONTITLEUPDATE,
	}
	permissionCategoryQuoteCapitalizationTitleRaffle PermissionCategory = []api.ConsentPermission{
		api.ConsentPermissionQUOTECAPITALIZATIONTITLERAFFLECREATE,
	}
	permissionCategoryContractPensionPlanLead PermissionCategory = []api.ConsentPermission{
		api.ConsentPermissionCONTRACTPENSIONPLANLEADCREATE,
		api.ConsentPermissionCONTRACTPENSIONPLANLEADUPDATE,
	}
	permissionCategoryContractPensionPlanLeadPortability PermissionCategory = []api.ConsentPermission{
		api.ConsentPermissionCONTRACTPENSIONPLANLEADPORTABILITYCREATE,
		api.ConsentPermissionCONTRACTPENSIONPLANLEADPORTABILITYUPDATE,
	}
	permissionCategoryContractLifePensionPlanLead PermissionCategory = []api.ConsentPermission{
		api.ConsentPermissionCONTRACTLIFEPENSIONLEADPORTABILITYCREATE,
		api.ConsentPermissionCONTRACTLIFEPENSIONLEADUPDATE,
	}
	permissionCategoryContractLifePensionPlanLeadPortability PermissionCategory = []api.ConsentPermission{
		api.ConsentPermissionCONTRACTLIFEPENSIONLEADPORTABILITYCREATE,
		api.ConsentPermissionCONTRACTLIFEPENSIONLEADPORTABILITYUPDATE,
	}
	permissionCategoryPensionWithdrawal PermissionCategory = []api.ConsentPermission{
		api.ConsentPermissionPENSIONWITHDRAWALCREATE,
	}
	permissionCategoryCapitalizationTitleWithdrawalWithdrawal PermissionCategory = []api.ConsentPermission{
		api.ConsentPermissionCAPITALIZATIONTITLEWITHDRAWALCREATE,
	}
)

var permissionCategories = []PermissionCategory{
	permissionCategoryPersonalRegistration,
	permissionCategoryBusinessRegistration,
	permissionCategoryCapitalizationTitle,
	permissionCategoryPensionPlan,
	permissionCategoryLifePensionPlan,
	permissionCategoryFinancialAssistence,
	permissionCategoryDamagesAndPeoplePatrimonial,
	permissionCategoryDamagesAndPeopleResponsibility,
	permissionCategoryDamagesAndPeopleTransport,
	permissionCategoryDamagesAndPeopleFinancialRisks,
	permissionCategoryDamagesAndPeopleRural,
	permissionCategoryDamagesAndPeopleAuto,
	permissionCategoryDamagesAndPeopleHousing,
	permissionCategoryDamagesAndPeopleAcceptanceAndBranchesAbroad,
	permissionCategoryDamagesAndPeoplePerson,
	permissionCategoryClaimNotificationRequestDamage,
	permissionCategoryClaimNotificationRequestPerson,
	permissionCategoryEndorsementRequest,
	permissionCategoryQuotePatrimonialLead,
	permissionCategoryQuotePatrimonialHome,
	permissionCategoryQuotePatrimonialCondominium,
	permissionCategoryQuotePatrimonialBusiness,
	permissionCategoryQuotePatrimonialDiverseRisks,
	permissionCategoryQuoteAcceptanceAndBranchesAbroadLead,
	permissionCategoryQuoteAutoLead,
	permissionCategoryQuoteAuto,
	permissionCategoryQuoteFinancialRiskLead,
	permissionCategoryQuoteHousingLead,
	permissionCategoryQuoteResponsibilityLead,
	permissionCategoryQuoteRuralLead,
	permissionCategoryQuoteTransportLead,
	permissionCategoryQuotePersonLead,
	permissionCategoryQuotePersonLifeAuto,
	permissionCategoryQuoteTravelAuto,
	permissionCategoryQuoteCapitalizationTitleLead,
	permissionCategoryQuoteCapitalizationTitle,
	permissionCategoryQuoteCapitalizationTitleRaffle,
	permissionCategoryContractPensionPlanLead,
	permissionCategoryContractPensionPlanLeadPortability,
	permissionCategoryContractLifePensionPlanLead,
	permissionCategoryContractLifePensionPlanLeadPortability,
	permissionCategoryPensionWithdrawal,
	permissionCategoryCapitalizationTitleWithdrawalWithdrawal,
}

type PermissionCategory []api.ConsentPermission

func (pc PermissionCategory) contains(p api.ConsentPermission) bool {
	return slices.Contains(pc, p)
}
